# Generated by Django 5.2.4 on 2025-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_order_card_name_order_card_number_order_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash On Delevery'), ('visa', 'Visa'), ('takeaway', 'Take Away')], default='cash', max_length=10),
        ),
    ]
